---
title: 'CV'
---
# Tejas Savalia
### PhD Candidate in Psychology, UMass Amherst

My research draws upon cognitive computational modeling to enable
investigations into cognitive aspects of implicit and explicit
learning. Broadly, I am interested in constructing neural and
computationally constrained models to draw quantifiable predictions
aimed at understanding the psychological processes of decision-making,
learning, and memory. I use behavioral and fMRI experiments to
investigate how models of cognition explain how humans learn and act
upon statistical regularities in their environments.

## Experience
### Industry Research Experience
- User Experience Research Intern, *Google, MTV (Summer 2023)*
    - Developed an end-to-end image processing pipeline to automate analysis of users’ phone grips. 
    - Validated with a 24-participant study and statistically quantified method reliability.
    - Developed a toolkit to vastly improve the efficiency and  scalability of conducting phone grip studies.
    - Presented the developed methodology and its validation study to an XFN audience.

- Quantitative User Experience Research Intern, *Google, NYC (Summer 2022)*
    - Developed a perceptual experimental framework to measure coherence of search page UI formats. 
    - Validated the developed metric using 42 MTurk studies with >20000 participants.

### Teaching Experience 

- Decision Making Seminar Instructor, *UMass Amherst* (Fall 2023)
    - Designed and taught weekly seminar on decision-making in Psychology. 

- Research Methods Teaching Assistant, *UMass Amherst* (Fall 2022, Spring 2023, Spring 2024)
    - Led weekly tutorials and hands-on laboratory sessions teaching students how to conduct end-to-end psychology research projects using survey designs, psychometric experiments, and R scripting

- Project Teaching Assitant *Neuromatch Academy* (Summer 2021)
    - Mentored teams of graduate and undergraduate students in the global summer school program through their projects on functional Magentic Resonance Imaging.

- Statistics Teaching Assistant, *UMass Amherst* (Spring 2020, Fall 2020)
    - Led labs and taught students how to use R to conduct data analyses.






## Current Projects
-   **Modeling statistical learning using Successor Representation**.
    Behavioral experiments and computational modeling to understand
    implicit learning of environment statistics and categorization.

-   **Bayesian modeling of instrumental learning in BPD patients**
    Bayesian computational modeling and analyses of data collected by
    clinical psychology collaborators to understand differences in
    decision-making behavior in borderline personality disorder
    patients.

-   **Understanding neural motor directional tuning using fMRI**
    Functional Neuroimaging experiments and computational modeling with
    multivariate analyses of neural tuning functions to investigate the
    neural correlates of motor directional planning.

-   **Understanding how the shape of data affects its perception**
    Applied research in collaboration with researchers in computer
    science using behavioral experiments and Bayesian drift-diffusion
    modeling to understand how data visualizations may bias perception
    in psychologically interpretable parameters.

## Publications
### Peer-reviewed Journal Articles
1. **Tejas Savalia**, Rosemary Cowell, and David Huber (2022). “Leap before you look”: Conditions that promote implicit visuomotor adaptation without explicit learning. [bioRxiv 2022-07](https://www.biorxiv.org/content/biorxiv/early/2022/07/13/2022.07.12.499675.full.pdf), *Under Review at Journal of Experimental Psychology, Human Perception and Performance8.

2. Elinor Waite, **Tejas Savalia**, Andrew Cohen,  Lauren Haliczer, Sarah Huffman, and Katherine Dixon-Gordon. Borderline personality disorder and learning: The influences of emotional state and social versus nonsocial feedback, [PsyArxiv, 2024](https://osf.io/preprints/psyarxiv/bkyse).*Under Review at Journal of Affective Disorders*.

3. **Tejas Savalia**, Andrew Lovett, Cristina Ceja, Rosemary Cowell, Cindy Xiong Bearfield, Local and Global Extrema and Recall Response Modalities Bias Position Recall in Line Charts. *Under Review at Transactions in Visualizations and Computer Graphics*.

4. **Tejas Savalia**, Cindy Xiong Bearfield. A case for using Psychological Process Models to measure Perceptual Biases in Data Visualizations *Under Review at ACM SIGCHI Late Breaking Work.*
    
5. **Tejas Savalia**, Anuj Shukla, and Raju S Bapi, A Unified Framework for Cognitive Sequencing. [*Frontiers in Psychology,  vol 7, (2016)*](https://www.frontiersin.org/journals/psychology/articles/10.3389/fpsyg.2016.01821/full). 

### Conference Presentations
1. **Tejas Savalia**, Jeffrey Starns, and Andrew Cohen, “Random walk length modulates structure acquisition in modular graphs,” [*COSYNE, 2024*](https://drive.google.com/file/d/1izGciiV_bXzsof3fHTlDrsKn195UB47A/view?usp=drive_link)

2. **Tejas Savalia**, Andrew Cohen, Rosemary Cowell, and David Huber. Reward changes are more disruptive than stimulus changes to implicit sequence learning of a community structure, *CEMS, 2023*.

3. **Tejas Savalia**, Rosemary Cowell and David Huber, "Leap before you look": Conditions that promote implicit visuomotor adaptation without explicit learning. *Talk  at Psychonomics, 2022*.

4. **Tejas Savalia**, Cristina Ceja, Rosemary Cowell, Cindy Xiong. "Estimating Biases in Line Charts: Effects of Shape and Response Modality". *OPAM, 2022*. 

5. **Tejas Savalia**, Cristina Ceja, Rosemary Cowell, Cindy Xiong. "Visual and Verbal Data Estimation Errors are Modulated by Chart Type". *Visual Science Society, 2022*. 

6. **Tejas Savalia**, Rosemary Cowell, David Huber, "Implicit Learning in Absence of Explicit Learning in a Visuomotor Adaptation Task." Poster Presentation in *Psychonomics, 2021.*

7. **Tejas Savalia**, Rosemary Cowell, David Huber, ``Learning to Learn: Modeling Time Course of Visuomotor Adaptation.'' Virtual poster presentation in *Annual meeting for the Society for Mathematical Psychology, 2020*. [Youtube Link](https://www.youtube.com/watch?v=vjP7YCm0bTU)

8. **Tejas Savalia**, Rosemary Cowell and David Huber, "Learning a novel perception-action mapping: Error magnitude, speed/accuracy emphasis, and reinforcement learning."  Poster Presentation in *Psychonomics, 2019.* 




