project:
  type: website
  output-dir: docs

website:
  title: "Tejas Savalia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - mds/about.qmd
      - mds/cv.qmd
    background: primary

format:
  html:
    theme: morph
    css: styles.css
    toc: true



