project:
    type: website
    output-dir: docs
    render:
        - mds/index.qmd
        - mds/cv.qmd


website:
    title: "Tejas Savalia"
    navbar:
        background: primary
        left:
            - mds/cv.qmd
        tools:
            - icon: twitter
              href: https://twitter.com/SavaliaTejas
            - icon: linkedin
              href: https://www.linkedin.com/in/tejas-savalia-8201888a/
            - icon: github
              href: https://github.com/tejas-savalia
            - text: "{{< iconify fa6-brands google-scholar >}}"
              href: https://scholar.google.com/citations?user=25KCLG8AAAAJ&hl=en

    google-analytics: "G-TEKMVKYLJF"
    open-graph: true


format:
    html:
        link-external-icon: true
        link-external-newwindow: true
        theme: darkly
        css: styles.css
        toc: true



