project:
    type: website
    output-dir: docs
    render:
        - mds/index.qmd
        - mds/cv.qmd

website:
    title: "Tejas Savalia"
    navbar:
        background: primary
    
        left:
            - text: "Home"
              file: mds/index.qmd
            - mds/cv.qmd

format:
    html:
        theme: morph
        css: styles.css
        toc: true



