project:
  type: website
  output-dir: docs

website:
  title: "Tejas Savalia"
  navbar:
    left:
      - href: mds/index.qmd
        text: Home
      - href: mds/about.qmd
        text: About
      - href: mds/cv.qmd
        text: CV
    background: primary

format:
  html:
    theme: morph
    css: styles.css
    toc: true



